"""
Invoice app URL configuration (v1)

- Handles invoice and invoice line endpoints
- Uses DRF routers for RESTful viewsets
- Linked from config.urls under /api/v1/
"""

from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import InvoiceViewSet, InvoiceLineViewSet

# DRF Router automatically generates:
# /invoices/       -> list, create
# /invoices/<id>/  -> retrieve, update, delete
# /invoicelines/   -> list, create
# /invoicelines/<id>/ -> retrieve, update, delete

router = DefaultRouter()
router.register('invoices', InvoiceViewSet)
router.register('invoicelines', InvoiceLineViewSet, basename='invoiceline')

urlpatterns = [
    path('', include(router.urls)),  # Include all routes generated by router
]
