# Generated by Django 5.2.7 on 2025-11-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('folio', models.CharField(blank=True, max_length=50, null=True)),
                ('guest_name', models.CharField(max_length=255)),
                ('pax', models.IntegerField(default=1)),
                ('bal_bf', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('acc', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('food', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bar', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('laundry', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('swimming', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('room_hire', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('t_charge', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('usd_swipe', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ecocash_zig', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('zig_swipe', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cash', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('t_ledger', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bank_tr', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bal_cf', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
