# Generated by Django 5.2.7 on 2025-11-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HouseStatusReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.CharField(max_length=20)),
                ('room_type', models.CharField(blank=True, max_length=50)),
                ('guest_name', models.CharField(blank=True, max_length=100)),
                ('organization', models.CharField(blank=True, max_length=100)),
                ('pax', models.PositiveIntegerField(default=1)),
                ('check_in', models.DateField(blank=True, null=True)),
                ('check_out', models.DateField(blank=True, null=True)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('out_of_order', models.BooleanField(default=False)),
                ('time', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'House Status Report',
                'verbose_name_plural': 'House Status Reports',
                'ordering': ['room_no'],
            },
        ),
    ]
