# Generated by Django 5.2.7 on 2025-11-17 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HouseStatusReport', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='housestatusreport',
            options={'ordering': ['room_no', 'check_in'], 'verbose_name': 'House Status Report', 'verbose_name_plural': 'House Status Reports'},
        ),
        migrations.AlterUniqueTogether(
            name='housestatusreport',
            unique_together={('room_no', 'check_in')},
        ),
    ]
