# Generated by Django 5.2.7 on 2025-11-10 08:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('arrival_date', models.DateField(default=django.utils.timezone.now)),
                ('departure_date', models.DateField(blank=True, null=True)),
                ('room_no', models.CharField(blank=True, max_length=20)),
                ('room_type', models.CharField(blank=True, max_length=50)),
                ('adults', models.PositiveIntegerField(default=1)),
                ('children', models.PositiveIntegerField(default=0)),
                ('rate_allocated', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('company_account_no', models.CharField(blank=True, max_length=50)),
                ('receptionist', models.CharField(blank=True, max_length=100)),
                ('vat_number', models.CharField(blank=True, default='10005237', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=255)),
                ('voucher', models.CharField(blank=True, max_length=100)),
                ('charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('credits', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='Invoice.invoice')),
            ],
        ),
    ]
