# Generated by Django 5.2.7 on 2025-11-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLedgerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('cash_balbf', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cash_acc', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cash_food', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cash_bar', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cash_laundry', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cash_swimming', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cash_roomhire', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cash_other', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cash_tcharge', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cash_usd', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cash_eco', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cash_zig', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cash_cash', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cash_tledger', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cash_banktr', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cash_balcf', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_balbf', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_acc', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_food', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_bar', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_laundry', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_swimming', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_roomhire', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_other', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_tcharge', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_usd', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_eco', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_zig', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_cash', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_tledger', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_banktr', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_balcf', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('debtors_in_res', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
